#
# Copyright (c) 2019-2022 Blue Clover Devices
#
# SPDX-License-Identifier: Apache-2.0
#

FROM ghcr.io/bcdevices/zephyr:3.0.0-0

WORKDIR /usr/src/

ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
