#
# Copyright (c) 2019-2021 Blue Clover Devices
#
# SPDX-License-Identifier: None
#

FROM ghcr.io/bcdevices/zephyr:2.7.0-1

WORKDIR /usr/src/

ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
